/*
 * This file is generated by jOOQ.
 */
package cn.bushadie.jooq.generator.tables.records;


import cn.bushadie.jooq.generator.tables.Userkv;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserkvRecord extends UpdatableRecordImpl<UserkvRecord> implements Record4<String, String, String, String> {

    private static final long serialVersionUID = -618934164;

    /**
     * Setter for <code>jooq.userkv.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>jooq.userkv.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>jooq.userkv.userid</code>.
     */
    public void setUserid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>jooq.userkv.userid</code>.
     */
    public String getUserid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>jooq.userkv.k</code>.
     */
    public void setK(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>jooq.userkv.k</code>.
     */
    public String getK() {
        return (String) get(2);
    }

    /**
     * Setter for <code>jooq.userkv.v</code>.
     */
    public void setV(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>jooq.userkv.v</code>.
     */
    public String getV() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Userkv.USERKV.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Userkv.USERKV.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Userkv.USERKV.K;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Userkv.USERKV.V;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getK();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getV();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getK();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getV();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserkvRecord value1(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserkvRecord value2(String value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserkvRecord value3(String value) {
        setK(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserkvRecord value4(String value) {
        setV(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserkvRecord values(String value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserkvRecord
     */
    public UserkvRecord() {
        super(Userkv.USERKV);
    }

    /**
     * Create a detached, initialised UserkvRecord
     */
    public UserkvRecord(String id, String userid, String k, String v) {
        super(Userkv.USERKV);

        set(0, id);
        set(1, userid);
        set(2, k);
        set(3, v);
    }
}
