/*
 * This file is generated by jOOQ.
 */
package cn.bushadie.jooq.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class User implements Serializable {

    private static final long serialVersionUID = 394055996;

    private String        id;
    private String        name;
    private Integer       age;
    private LocalDateTime modified;

    public User() {}

    public User(User value) {
        this.id = value.id;
        this.name = value.name;
        this.age = value.age;
        this.modified = value.modified;
    }

    public User(
        String        id,
        String        name,
        Integer       age,
        LocalDateTime modified
    ) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.modified = modified;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getAge() {
        return this.age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public LocalDateTime getModified() {
        return this.modified;
    }

    public void setModified(LocalDateTime modified) {
        this.modified = modified;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("User (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(age);
        sb.append(", ").append(modified);

        sb.append(")");
        return sb.toString();
    }
}
