/*
 * This file is generated by jOOQ.
 */
package cn.bushadie.jooq.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userinfo implements Serializable {

    private static final long serialVersionUID = 677238068;

    private String id;
    private String userid;
    private String address;

    public Userinfo() {}

    public Userinfo(Userinfo value) {
        this.id = value.id;
        this.userid = value.userid;
        this.address = value.address;
    }

    public Userinfo(
        String id,
        String userid,
        String address
    ) {
        this.id = id;
        this.userid = userid;
        this.address = address;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserid() {
        return this.userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Userinfo (");

        sb.append(id);
        sb.append(", ").append(userid);
        sb.append(", ").append(address);

        sb.append(")");
        return sb.toString();
    }
}
