/*
 * This file is generated by jOOQ.
 */
package cn.bushadie.jooq.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Userkv implements Serializable {

    private static final long serialVersionUID = 1072468285;

    private String id;
    private String userid;
    private String k;
    private String v;

    public Userkv() {}

    public Userkv(Userkv value) {
        this.id = value.id;
        this.userid = value.userid;
        this.k = value.k;
        this.v = value.v;
    }

    public Userkv(
        String id,
        String userid,
        String k,
        String v
    ) {
        this.id = id;
        this.userid = userid;
        this.k = k;
        this.v = v;
    }

    public String getId() {
        return this.id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getUserid() {
        return this.userid;
    }

    public void setUserid(String userid) {
        this.userid = userid;
    }

    public String getK() {
        return this.k;
    }

    public void setK(String k) {
        this.k = k;
    }

    public String getV() {
        return this.v;
    }

    public void setV(String v) {
        this.v = v;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Userkv (");

        sb.append(id);
        sb.append(", ").append(userid);
        sb.append(", ").append(k);
        sb.append(", ").append(v);

        sb.append(")");
        return sb.toString();
    }
}
