/*
 * This file is generated by jOOQ.
 */
package cn.bushadie.jooq.generator.tables.daos;


import cn.bushadie.jooq.generator.tables.Userkv;
import cn.bushadie.jooq.generator.tables.records.UserkvRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UserkvDao extends DAOImpl<UserkvRecord, cn.bushadie.jooq.generator.tables.pojos.Userkv, String> {

    /**
     * Create a new UserkvDao without any configuration
     */
    public UserkvDao() {
        super(Userkv.USERKV, cn.bushadie.jooq.generator.tables.pojos.Userkv.class);
    }

    /**
     * Create a new UserkvDao with an attached configuration
     */
    @Autowired
    public UserkvDao(Configuration configuration) {
        super(Userkv.USERKV, cn.bushadie.jooq.generator.tables.pojos.Userkv.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.bushadie.jooq.generator.tables.pojos.Userkv object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.bushadie.jooq.generator.tables.pojos.Userkv> fetchById(String... values) {
        return fetch(Userkv.USERKV.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.bushadie.jooq.generator.tables.pojos.Userkv fetchOneById(String value) {
        return fetchOne(Userkv.USERKV.ID, value);
    }

    /**
     * Fetch records that have <code>userid IN (values)</code>
     */
    public List<cn.bushadie.jooq.generator.tables.pojos.Userkv> fetchByUserid(String... values) {
        return fetch(Userkv.USERKV.USERID, values);
    }

    /**
     * Fetch records that have <code>k IN (values)</code>
     */
    public List<cn.bushadie.jooq.generator.tables.pojos.Userkv> fetchByK(String... values) {
        return fetch(Userkv.USERKV.K, values);
    }

    /**
     * Fetch records that have <code>v IN (values)</code>
     */
    public List<cn.bushadie.jooq.generator.tables.pojos.Userkv> fetchByV(String... values) {
        return fetch(Userkv.USERKV.V, values);
    }
}
