/*
 * This file is generated by jOOQ.
 */
package cn.bushadie.jooq.generator.tables.daos;


import cn.bushadie.jooq.generator.tables.Userinfo;
import cn.bushadie.jooq.generator.tables.records.UserinfoRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Repository;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
@Repository
public class UserinfoDao extends DAOImpl<UserinfoRecord, cn.bushadie.jooq.generator.tables.pojos.Userinfo, String> {

    /**
     * Create a new UserinfoDao without any configuration
     */
    public UserinfoDao() {
        super(Userinfo.USERINFO, cn.bushadie.jooq.generator.tables.pojos.Userinfo.class);
    }

    /**
     * Create a new UserinfoDao with an attached configuration
     */
    @Autowired
    public UserinfoDao(Configuration configuration) {
        super(Userinfo.USERINFO, cn.bushadie.jooq.generator.tables.pojos.Userinfo.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(cn.bushadie.jooq.generator.tables.pojos.Userinfo object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<cn.bushadie.jooq.generator.tables.pojos.Userinfo> fetchById(String... values) {
        return fetch(Userinfo.USERINFO.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public cn.bushadie.jooq.generator.tables.pojos.Userinfo fetchOneById(String value) {
        return fetchOne(Userinfo.USERINFO.ID, value);
    }

    /**
     * Fetch records that have <code>userid IN (values)</code>
     */
    public List<cn.bushadie.jooq.generator.tables.pojos.Userinfo> fetchByUserid(String... values) {
        return fetch(Userinfo.USERINFO.USERID, values);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<cn.bushadie.jooq.generator.tables.pojos.Userinfo> fetchByAddress(String... values) {
        return fetch(Userinfo.USERINFO.ADDRESS, values);
    }
}
