/*
 * This file is generated by jOOQ.
 */
package cn.bushadie.jooq.generator;


import cn.bushadie.jooq.generator.tables.User;
import cn.bushadie.jooq.generator.tables.Userinfo;
import cn.bushadie.jooq.generator.tables.Userkv;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Jooq extends SchemaImpl {

    private static final long serialVersionUID = 1671592232;

    /**
     * The reference instance of <code>jooq</code>
     */
    public static final Jooq JOOQ = new Jooq();

    /**
     * The table <code>jooq.user</code>.
     */
    public final User USER = cn.bushadie.jooq.generator.tables.User.USER;

    /**
     * The table <code>jooq.userinfo</code>.
     */
    public final Userinfo USERINFO = cn.bushadie.jooq.generator.tables.Userinfo.USERINFO;

    /**
     * The table <code>jooq.userkv</code>.
     */
    public final Userkv USERKV = cn.bushadie.jooq.generator.tables.Userkv.USERKV;

    /**
     * No further instances allowed
     */
    private Jooq() {
        super("jooq", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            User.USER,
            Userinfo.USERINFO,
            Userkv.USERKV);
    }
}
