/*
 * This file is generated by jOOQ.
 */
package cn.bushadie.jooq.generator;


import cn.bushadie.jooq.generator.tables.User;
import cn.bushadie.jooq.generator.tables.Userinfo;
import cn.bushadie.jooq.generator.tables.Userkv;
import cn.bushadie.jooq.generator.tables.records.UserRecord;
import cn.bushadie.jooq.generator.tables.records.UserinfoRecord;
import cn.bushadie.jooq.generator.tables.records.UserkvRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>jooq</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = UniqueKeys0.KEY_USER_PRIMARY;
    public static final UniqueKey<UserRecord> SYNTHETIC_PK_USER = UniqueKeys0.SYNTHETIC_PK_USER;
    public static final UniqueKey<UserinfoRecord> KEY_USERINFO_PRIMARY = UniqueKeys0.KEY_USERINFO_PRIMARY;
    public static final UniqueKey<UserinfoRecord> SYNTHETIC_PK_USERINFO = UniqueKeys0.SYNTHETIC_PK_USERINFO;
    public static final UniqueKey<UserkvRecord> KEY_USERKV_PRIMARY = UniqueKeys0.KEY_USERKV_PRIMARY;
    public static final UniqueKey<UserkvRecord> SYNTHETIC_PK_USERKV = UniqueKeys0.SYNTHETIC_PK_USERKV;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, "KEY_user_PRIMARY", User.USER.ID);
        public static final UniqueKey<UserRecord> SYNTHETIC_PK_USER = Internal.createUniqueKey(User.USER, "SYNTHETIC_PK_user", User.USER.ID);
        public static final UniqueKey<UserinfoRecord> KEY_USERINFO_PRIMARY = Internal.createUniqueKey(Userinfo.USERINFO, "KEY_userinfo_PRIMARY", Userinfo.USERINFO.ID);
        public static final UniqueKey<UserinfoRecord> SYNTHETIC_PK_USERINFO = Internal.createUniqueKey(Userinfo.USERINFO, "SYNTHETIC_PK_userinfo", Userinfo.USERINFO.ID);
        public static final UniqueKey<UserkvRecord> KEY_USERKV_PRIMARY = Internal.createUniqueKey(Userkv.USERKV, "KEY_userkv_PRIMARY", Userkv.USERKV.ID);
        public static final UniqueKey<UserkvRecord> SYNTHETIC_PK_USERKV = Internal.createUniqueKey(Userkv.USERKV, "SYNTHETIC_PK_userkv", Userkv.USERKV.ID);
    }
}
