/*
 * This file is generated by jOOQ.
 */
package cn.bushadie.jooq.generator;


import cn.bushadie.jooq.generator.tables.User;
import cn.bushadie.jooq.generator.tables.Userinfo;
import cn.bushadie.jooq.generator.tables.Userkv;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in jooq
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>jooq.user</code>.
     */
    public static final User USER = cn.bushadie.jooq.generator.tables.User.USER;

    /**
     * The table <code>jooq.userinfo</code>.
     */
    public static final Userinfo USERINFO = cn.bushadie.jooq.generator.tables.Userinfo.USERINFO;

    /**
     * The table <code>jooq.userkv</code>.
     */
    public static final Userkv USERKV = cn.bushadie.jooq.generator.tables.Userkv.USERKV;
}
